import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h1 className="text-2xl font-bold text-cyan-300">
            Create T3 App
          </h1>

          <h3>This stack uses:</h3>

        </div>
      </div>
    </>
  );
};

export default Home;



