
import type { NextPage } from "next";
import Head from "next/head";
import { prisma } from "../db/client";

const Home: NextPage = (props: any) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h1 className="text-2xl font-bold text-cyan-300">
            Create T3 App
          </h1>

          <h3>This stack uses:</h3>
          <p>{props.questions}</p>
        </div>
      </div>
    </>
  );
};

export const getStaticProps = async () => {
  const questions = await prisma.voteQuestion.findMany();
  return {
    props: {
      questions: JSON.stringify(questions),
    },  
  }
};

export default Home;